# Autogenerated by devscripts/update-version.py

__version__ = '2025.11.20.120337'

RELEASE_GIT_HEAD = '16e4805485c4811ab602eb1728e220186b963b66'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'muhammadiighra/yt-dlp'

ORIGIN = 'muhammadiighra/yt-dlp'

_pkg_version = '2025.11.20.120337'
